Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: test
      Version: "1.26"
      RoleArn: "arn:aws:iam::484537997968:role/eks-cluster"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-0b86ec844cc577f57
        SubnetIds:
          - subnet-098b1454683bddabc
          - subnet-089b07c2d1da2849f
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit     