Resources:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: test
      NodeRole: 'arn:aws:iam::484537997968:role/eksnode_role'
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      AmiType: ami-0453898e98046c639  
      Subnets:
        - subnet-0fd66e1ca42affd13
        - subnet-09f73f1bb509444d0
      InstanceTypes: 
        - t2.micro
