Resources:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: test
      NodeRole: 'arn:aws:iam::484537997968:role/eksnode_role'
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3  
      Subnets:
        - subnet-0be0a525c28f4a3c1
        - subnet-0c86a0865fcea224d
      InstanceTypes: 
        - t2.micro
