
Resources:
 InstanceSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Allow http to client host
     VpcId: vpc-0c8e9966c66d73040
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 100
         CidrIp: 0.0.0.0/0
     SecurityGroupEgress:
       - IpProtocol: -1
         FromPort: -1
         ToPort: -1
         CidrIp: 0.0.0.0/0