
Resources:
 InstanceSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Allow http to client host
     VpcId: vpc-0cafdc7294b3ee274
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 0
         ToPort: 1000
         CidrIp: 0.0.0.0/0
     SecurityGroupEgress:
       - IpProtocol: tcp
         FromPort: 0
         ToPort: 1000
         CidrIp: 0.0.0.0/0