apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
        user nginx;
        worker_processes auto;
        error_log /var/log/nginx/error.log;
        pid /run/nginx.pid;
        # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
        include /usr/share/nginx/modules/*.conf;
        events {
            worker_connections 1024;
        }
        http {
            log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';
            access_log  /var/log/nginx/access.log  main;
            client_max_body_size 500m;
            sendfile            on;
            tcp_nopush          on;
            tcp_nodelay         on;
            keepalive_timeout   520;
            types_hash_max_size 2048;
            include             /etc/nginx/mime.types;
            default_type        application/octet-stream;
            # Load modular configuration files from the /etc/nginx/conf.d directory.
            # See http://nginx.org/en/docs/ngx_core_module.html#include
            # for more information.
            #include /etc/nginx/conf.d/*.conf;
            
            proxy_hide_header 'X-XSS-Protection';
            map $http_upgrade $connection_upgrade {
                default upgrade;
                '' close;
            }
            
            upstream app_shell {
                server 10.9.131.124:30602;
                #server 10.9.131.124:32200;
            }
            # upstream fastlcasvc {
            #     server 10.9.131.124:32282;
            # }
            upstream fastlca-svc-v2 {
                server 10.9.131.124:32285;
            }   
            upstream report-builder-v2 {
                server 10.9.131.124:32290;
            } 
            upstream strapi-svc-v2 {
                server 10.9.131.124:32287;
            }             
            # upstream fastlcaapp {
            #     server 10.9.131.124:32200;
            # }
            # upstream mockserver {
            #     server 10.9.131.124:32201;
            # }
            upstream bhauth {
                server 10.9.131.124:32280;
            }
            upstream svc-fastlci-app {
                server 10.9.131.124:32500;
            }
            upstream bhusermgmt {
                server 10.9.131.124:32283;
            }
            upstream wsconnect {
                server 10.9.131.124:30603;
            }
            # upstream app_store {
            #     server 10.9.131.124:30230;
            # }
            # upstream widget_store {
            #     server 10.9.131.124:30100;
            # }
            upstream svc-fastlci-svc {
                server 10.9.131.124:32284;
            }
            # upstream query_executor {
            #     server 10.9.131.124:30755;
            # }
            
          
            server {
                gzip on;
                gzip_comp_level 5;
                gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/rss+xml text/javascript image/x-icon image/bmp image/svg+xml;
                gzip_proxied no-cache no-store private expired auth;
                gzip_min_length 1000;
                proxy_pass_header Server;
                add_header X-Frame-Options SAMEORIGIN always;
                add_header X-XSS-Protection "1; mode=block";
                add_header X-Content-Type-Options nosniff;
                listen       0.0.0.0:80;
                server_name  fast.lca.services.com;
                root         /usr/share/nginx/html;
                # Load configuration files for the default server block.
                #include /etc/nginx/default.d/*.conf;
                
                location / {
                  proxy_redirect off;
                  #proxy_pass http://svc-fastlci-app;
                  proxy_pass http://app_shell;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection $connection_upgrade;
                  proxy_read_timeout 900;
                  proxy_connect_timeout 900;
                  proxy_send_timeout 900;
                }
              
                location /bh-auth {
                rewrite /bh-auth/(.*)$ /$1 break;
                proxy_pass http://bhauth;
                }
                # location /fastlca-app {
                #  rewrite /fastlca-app/(.*)$ /$1 break;
                #  proxy_pass http://fastlcaapp;
                #  proxy_http_version 1.1;
                #   proxy_set_header Upgrade $http_upgrade;
                #   proxy_set_header Connection $connection_upgrade;
                #   include             /etc/nginx/mime.types;
                #  }
                 
                 location /fastlci-app {
                 rewrite /fastlci-app/(.*)$ /$1 break;
                 proxy_pass http://svc-fastlci-app;
                 proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection $connection_upgrade;
                  include             /etc/nginx/mime.types;
                 }
                 
                #  location /appstore {
                #    #rewrite /appstore/(.*)$ /$1 break;
                #    proxy_pass http://app_store;
                #  }
                 
                #  location /query-executor {
                #    #rewrite /query-executor/(.*)$ /$1 break;
                #    proxy_pass http://query_executor;
                #    proxy_connect_timeout 86400;
                #    proxy_read_timeout 86400;
                #    proxy_send_timeout 86400;
                #    send_timeout 86400;
                #  }
        
                #  location /widgetstore {
                #    #rewrite /widgetstore/(.*)$ /$1 break;
                #    proxy_pass http://widget_store;
                #  }
                 
                # location /mock-server {
                #  rewrite /mock-server/(.*)$ /$1 break;
                #  proxy_pass http://mockserver;
                # }
                # location /fastlca-svc/ {
                #   rewrite /fastlca-svc/(.*)$ /$1 break;
                #   proxy_pass http://fastlcasvc;
                #   proxy_http_version 1.1;
                #   proxy_set_header X-Forwarded-Host $host;
                #   proxy_set_header X-Forwarded-Server $host;
                #   proxy_set_header X-Real-IP $remote_addr;
                #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #   proxy_set_header X-Forwarded-Proto $scheme;
                #   proxy_set_header Host $http_host;
                #   proxy_set_header Upgrade $http_upgrade;
                #   proxy_set_header Connection "Upgrade";
                #   proxy_pass_request_headers on;
                #  }
                #   location /fastlca-svc/assets/ {
                #   rewrite /fastlca-svc/(.*) /$1  break;
                #   proxy_pass http://fastlcasvc/assets;
                #   proxy_http_version 1.1;
                #   proxy_set_header X-Forwarded-Host $host;
                #   proxy_set_header X-Forwarded-Server $host;
                #   proxy_set_header X-Real-IP $remote_addr;
                #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #   proxy_set_header X-Forwarded-Proto $scheme;
                #   proxy_set_header Host $http_host;
                #   proxy_set_header Upgrade $http_upgrade;
                #   proxy_set_header Connection "Upgrade";
                #   proxy_pass_request_headers on;
                # }

                location /report-builder-v2/ {
                  rewrite /report-builder-v2/(.*)$ /$1 break;
                  proxy_pass http://report-builder-v2;
                  proxy_http_version 1.1;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_set_header X-Forwarded-Server $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Host $http_host;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_pass_request_headers on;
                  proxy_read_timeout 2000;
                  proxy_connect_timeout 2000;
                  proxy_send_timeout 2000;
                 }

                location /fastlca-strapi-svc-v2/ {
                  rewrite /fastlca-strapi-svc-v2/(.*)$ /$1 break;
                  proxy_pass http://strapi-svc-v2;
                  proxy_http_version 1.1;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_set_header X-Forwarded-Server $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Host $http_host;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_pass_request_headers on;
                 }
                  location /fastlca-strapi-svc-v2/assets/ {
                  rewrite /fastlca-strapi-svc-v2/(.*) /$1  break;
                  proxy_pass http://strapi-svc-v2/assets;
                  proxy_http_version 1.1;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_set_header X-Forwarded-Server $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Host $http_host;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_pass_request_headers on;
                }
          
                location /fastlca-svc-v2 {
                  rewrite /fastlca-svc-v2/(.*)$ /$1 break;
                  proxy_pass http://svc-fastlca-svc-v2;
                  proxy_http_version 1.1;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_set_header X-Forwarded-Server $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Host $http_host;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_pass_request_headers on;
                  proxy_read_timeout 900;
                  proxy_connect_timeout 900;
                  proxy_send_timeout 900;
                 }          
                 
                # location /strapi-svc-v2 {
                #   rewrite /strapi-svc-v2/(.*)$ /$1 break;
                #   proxy_pass http://strapi-svc-v2;
                #   proxy_http_version 1.1;
                #   proxy_set_header X-Forwarded-Host $host;
                #   proxy_set_header X-Forwarded-Server $host;
                #   proxy_set_header X-Real-IP $remote_addr;
                #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #   proxy_set_header X-Forwarded-Proto $scheme;
                #   proxy_set_header Host $http_host;
                #   proxy_set_header Upgrade $http_upgrade;
                #   proxy_set_header Connection "Upgrade";
                #   proxy_pass_request_headers on;
                #  }                           
                 
                location /fastlca-svc-v2/assets/ {
                  rewrite /fastlca-svc-v2/(.*) /$1  break;
                  proxy_pass http://fastlca-svc-v2/assets;
                  proxy_http_version 1.1;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_set_header X-Forwarded-Server $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Host $http_host;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_pass_request_headers on;
                }
                
                location /dashboard {
                  proxy_pass http://strapi-svc-v2/dashboard;
                  proxy_http_version 1.1;
                  proxy_set_header X-Forwarded-Host $host;
                  proxy_set_header X-Forwarded-Server $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Host $http_host;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_pass_request_headers on;
                }
                
                # location /dashboard {
                #   proxy_pass http://fastlcasvc/dashboard;
                #   proxy_http_version 1.1;
                #   proxy_set_header X-Forwarded-Host $host;
                #   proxy_set_header X-Forwarded-Server $host;
                #   proxy_set_header X-Real-IP $remote_addr;
                #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #   proxy_set_header X-Forwarded-Proto $scheme;
                #   proxy_set_header Host $http_host;
                #   proxy_set_header Upgrade $http_upgrade;
                #   proxy_set_header Connection "Upgrade";
                #   proxy_pass_request_headers on;
                # }
                 
                 location /fastlci-svc {
                  rewrite /fastlci-svc/(.*)$ /$1 break;
                  proxy_pass http://svc-fastlci-svc;
                 }
                # location /bh-usermgmt {
                # rewrite /bh-usermgmt/(.*)$ /$1 break;
                # proxy_pass http://bhusermgmt;
                #}
                location /socket.io/ {
                 proxy_pass http://wsconnect;
                 proxy_redirect off;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection "upgrade";
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                }
                #location /appbuilder {
                 #rewrite /appbuilder/(.*)$ /$1 break;
                 #proxy_pass http://10.9.131.124:30702;
                #}
             location /argocd {
               proxy_redirect off;
               proxy_pass http://argocd-server.argocd;
               proxy_http_version 1.1; # this is essential for chunked responses to work
               proxy_buffering    off;
               proxy_set_header   X-Real-IP $remote_addr;
               proxy_set_header   X-Scheme $scheme;
               proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header   Host $http_host;
              }

              # Object store Code starts from here 
             # location /zenko {
               # rewrite /zenko/(.*)$ /$1 break;
               # proxy_pass http://zenko-svc:8000;
              #}

              #location /zenko/live {
              #  rewrite /zenko/live/(.*)$ /$1 break;
              #  rewrite /zenko/(.*)$ /$1 break;
              #  proxy_pass http://zenko-svc:8002;
             # }

             # location /zenko/ready {
              #  rewrite /zenko/(.*)$ /$1 break;
              #  proxy_pass http://zenko-svc:8002;
             # }
              location /dfc-svc {
                rewrite /dfc-svc/(.*)$ /$1 break;
                proxy_pass http://svc-dfc-service;             
              }
              location /bh-usermgmt {
                rewrite /bh-usermgmt/(.*)$ /$1 break;
                proxy_pass http://svc-user-mgmt:80;
              }             
             
              location /notification-svc { 
                rewrite /notification-svc/(.*)$ /$1 break; 
                proxy_pass http://svc-notification:80;
              }
              
              location /object-storage {
                rewrite /object-storage/(.*)$ /$1 break;
                proxy_pass http://svc-objectstorage-service:80;
              }
              
              location /ns-admin-console{
                rewrite /ns-admin-console/(.*)$ /$1 break;
                proxy_pass http://svc-ns-admin-console;
              }

        }
        }
